apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

group = 'expo.modules.serviciosocket'
version = '0.1.0'

android {
  namespace "expo.modules.serviciosocket"
  compileSdk 36
  defaultConfig { minSdk 24 }
  kotlinOptions { jvmTarget = "17" }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}

repositories { mavenCentral() }

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}"
}
